### ISSUE TITLE
disponibilização do dataset

### ISSUE THREAD

**Issue by gondimjoaom** [larocs/PraCegoVer#1]
Olá, vocês vão colocar o dataset aqui? Está em outro link?

**Comment by gabrielsantosrv** [comment]
Olá @gondimjoaom! Muito obrigado pelo interesse  ;)

Nós estamos no processo de submissão do artigo, então assim que for publicado, nós disponibilizaremos a base nesse mesmo repositório.

**Comment by gondimjoaom** [comment]
Ah entendi! Tinha visto o artigo no arxiv e me apressei pelo interesse mesmo! Sou mestrando em computação na UFBA (grupo FORMAS) e tava procurando datasets em português para image captioning. Fico no aguardo então!

**Comment by hereismari** [comment]
@gabrielsantosrv poderia deixar o issue aberto para quem tiver interessado receber notificacao? Se achar melhor pode criar um issue novo tbm, mas gostaria de saber quando o dataset estiver disponivel :)

**Comment by gabrielsantosrv** [comment]
> @gabrielsantosrv poderia deixar o issue aberto para quem tiver interessado receber notificacao? Se achar melhor pode criar um issue novo tbm, mas gostaria de saber quando o dataset estiver disponivel :)

@hereismari, sem problemas, eu vou deixar esse issue aberto. Assim, que o artigo for publicado eu já atualizo o repositório com a base :D

**Comment by gondimjoaom** [comment]
veio aí? :eyes:

**Comment by gabrielsantosrv** [comment]
Pessoal, só avisando que finalmente vamos liberar a base \0/
Segue o link para o nosso artigo: https://www.mdpi.com/2306-5729/7/2/13. Lá vcs encontram o link para o download da base :D  Em breve vou atualizar o readme desse repo.

**Comment by gabrielsantosrv** [comment]
Estou fechando essa issue, pois já atualizei o README com todas as informações necessárias para o download.

**Comment by gabrielsantosrv** [comment]
Estou fechando essa issue, pois já atualizei o README com todas as informações necessárias para o download.
