### ISSUE TITLE
When will the data set be available for download?

### ISSUE THREAD

**Issue by tianjunyu0871** [larocs/PraCegoVer#2]
When will the data set be available for download?

**Comment by gabrielsantosrv** [comment]
@tianjunyu0871 we have submitted our paper to a journal, and as soon as it is published, we will release the dataset for download.

**Comment by tianjunyu0871** [comment]
thank you for your reply. I urgently need the insta-1.1M data set recently. Can you provide a link to the google network disk for me to download? thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "larocs/PraCegoVer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 晚上11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [larocs/PraCegoVer] When will the data set be available for download? (#2)





 
@tianjunyu0871 we have submitted our paper to a journal, and as soon as it is published, we will release the dataset for download.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gabrielsantosrv** [comment]
We have made the dataset available on Zenodo (https://zenodo.org/record/5710562), a thorough description can be found on README.
