### ISSUE TITLE
Request for the dataset.json

### ISSUE THREAD

**Issue by RitaRamo** [larocs/PraCegoVer#3]
Hi,

Thanks a lot for providing such a useful resource! 

For research purposes, I need the dataset for a research paper as soon as possible. I've already asked about the permission but still waiting. Would it be possible to provide the dataset.json (without the images)? 

I would really appreciate, thanks in advance.

**Comment by gabrielsantosrv** [comment]
Hi, Rita!

I just accepted your request,  so you can  download  dataset.json and
images separately.

Thanks for your interest,

Best regards,

Gabriel Oliveira

**Comment by RitaRamo** [comment]
Muito obrigada!
